### ISSUE TITLE
Return more info from the Send Push API response after sending a notification

### ISSUE THREAD

**Issue by franciscohanna92** [pushy-me/pushy-node#13]
The [Send Push API](https://pushy.me/docs/api/send-notifications) response is the following:
```json
{
    "success": true,
    "id": "5ea9b214b47cad768a35f13a",
    "info": {
        "devices": 2,
        "failed": ["9d1096fe0c58670dad2116"]
    }
}
```

But currently this library only returns the push ID
https://github.com/pushy/pushy-node/blob/10e8fd94986fdcf661def8a0cd9f6adbf24d8059/api/push/send.js#L99

I think it will be valuable to return the following (or we could also return the complete API response):
```json
{
    "id": "5ea9b214b47cad768a35f13a",
    "devices": 2,
    "failed": ["9d1096fe0c58670dad2116"]
}
```

This would be a breaking change. As an alternative we could also add it as another return parameter and keep returning the push ID first (but this isn't a desirable API design).

**Comment by pushy** [comment]
Thanks so much for the suggestion, @franciscohanna92! This has now been completed in https://github.com/pushy/pushy-node/commit/8fb3fbe6c3e6b80e19372ca1bee8734421920d6d and published to `npm` in major version `3.0.0` as it is indeed a breaking change.

**Comment by franciscohanna92** [comment]
@pushy That's great!

Be aware that the response type needs to be updated
https://github.com/pushy/pushy-node/blob/9c16009182a8e5bfa4417a2d96926d49a7789912/index.d.ts#L247

**Comment by pushy** [comment]
@franciscohanna92 Thanks for taking care of this in #15!
