### ISSUE TITLE
Replace deprecated dependencies

### ISSUE THREAD

**Issue by franciscohanna92** [pushy-me/pushy-node#14]
The SDK has two dependencies:
- `request`, which has been [officially deprecated](https://github.com/request/request#deprecated).
- `bluebird`, which [their authors recommend](https://github.com/petkaantonov/bluebird#%EF%B8%8Fnote%EF%B8%8F) stop using in favor of native Promises.

To keep Pushy's Node library up to date with modern practices and spec compliant APIs I propose:
- replace `request` with a modern (and spec compliant) library like [undici](https://github.com/nodejs/undici)
- drop `bluebird` in favor of Node's native Promise API.

**Comment by pushy** [comment]
Hi @franciscohanna92,
Thanks so much for bringing this to our attention! 

1) We've removed dependency on `bluebird` in https://github.com/pushy-me/pushy-node/commit/e4a50a5155799161298e4e9d5b07270948f824ad.

2) We've migrated from `request` to `axios` in https://github.com/pushy-me/pushy-node/commit/83f75d71905740a88f95c6b0ef3da739480b1bf4 to maintain compatibility with older Node.js versions (`undici` requires `Node 12.18` and up).

These changes will soon be published to `npm` in version `3.0.1`.
