### ISSUE TITLE
UnhandledPromiseRejection when Pushy API response is 4xx 

### ISSUE THREAD

**Issue by franciscohanna92** [pushy-me/pushy-node#21]
I'm just noticing that in the [migration to axios](https://github.com/pushy/pushy-node/commit/83f75d71905740a88f95c6b0ef3da739480b1bf4) the promise chain is being broken by rejecting inside a catch block:
https://github.com/pushy/pushy-node/blob/cc2dd533cad35954f83a33b1e1b2430123cbfe96/api/push/send.js#L97

This is crashing our app with an `UnhandledPromiseRejection` exception.

**Comment by pushy** [comment]
Hi @franciscohanna92,
Thanks for creating this issue. 

If you're using promises when invoking the various Pushy APIs, please make sure to define a `.catch()` block as follows:

```
pushy.sendPushNotification(data, tokens, options)
    .then(function (result) {
        // Log success
        console.log('Push sent successfully! (ID: ' + result.id + ')');
    }).catch(function (err) {
        // Log errors to console
        return console.error(err);
    });
```

**Note:**  The `.catch()` block must be chained directly after the `.then()` block to avoid the exception.

When we omitted the `.catch()` block and only defined a `.then()` block, indeed, the `UnhandledPromiseRejection` crashed the process, which is expected Node.js behavior.

Please let us know if this resolves your issue.
