### ISSUE TITLE
Incorrect Return Type for `getTopics`

### ISSUE THREAD

**Issue by Lycrios** [pushy-me/pushy-node#22]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `pushy@3.0.2` for the project I'm working on.

The return type from the pushy `getTopics` function was incorrect.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/pushy/index.d.ts b/node_modules/pushy/index.d.ts
index 0c73e71..3856e0a 100644
--- a/node_modules/pushy/index.d.ts
+++ b/node_modules/pushy/index.d.ts
@@ -345,7 +345,7 @@ declare module 'pushy' {
          * Retrieve a list of your app's topics and subscribers count.
          * @see {@link https://pushy.me/docs/api/pubsub-topics}
          */
-        getTopics(): Promise<Array<TopicStatus>>;
+        getTopics(): Promise<{topics: TopicStatus[]}>;
 
         /**
          * Retrieve a list of devices subscribed to a certain topic.
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by pushy** [comment]
Hi @Lycrios,
Thanks so much for creating this issue and providing a solution.

We've updated `index.d.ts` accordingly in [b33f947](https://github.com/pushy/pushy-node/commit/b33f947cf94c5dbe0348c14adfd98be6f2a377c1) and released version `3.0.3` to `npm`.

Please let us know if there's anything else we can help with.
