### ISSUE TITLE
Error : the VAPID credentials in the authorization header do not correspond to the credentials used to create the subscriptions.

### ISSUE THREAD

**Issue by nueng-fazwaz** [pushy-me/pushy-node#23]
I got this error when I send web push notification.
```
{
   "statusCode": 403,
   "body": "the VAPID credentials in the authorization header do not correspond to the credentials used to create the subscriptions.\n",
   "name":"WebPushError",
   "message":"Received unexpected response code"
}
```

**Comment by pushy** [comment]
Hi @nueng-fazwaz,
Thanks for reaching out. We'd be glad to assist.

This error may occur if your website has previously registered a service worker for push notifications using a different service than Pushy with different VAPID credentials.

To resolve the issue, your app can programmatically unregister the non-Pushy active service workers before calling `Pushy.register()`:

```
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.getRegistrations()
        .then(function (registrations) {
            for (let registration of registrations) {
                if (!registration.active.scriptURL.includes('service-worker.js'){
                    registration.unregister();
                }
            }
        });
}
```

**Comment by nueng-fazwaz** [comment]
It not work, I don't know why not work, I test on ngrok domain it can receive notification but on localhost and my domain doesn't receive notification.
my website use Next.js

this is my service-worker.js
```
self.addEventListener('push', function (event) {
    // Extract payload as JSON object, default to empty object
    var payload = event.data.json() || {}
    var data = payload.data || payload

    const messageChannel = new BroadcastChannel('msg-channel')
    messageChannel.postMessage({ data })
})

self.addEventListener(
    'notificationclick',
    function (event) {
        event.notification.close()
        event.waitUntil(
            clients
                .matchAll({
                    type: 'window'
                })
                .then((clientList) => {
                    for (const client of clientList) {
                        if ('focus' in client) return client.focus()
                    }
                })
        )
    },
    false
)
```

**Comment by pushy** [comment]
Hi @nueng-fazwaz,
Please try manually deleting your installed service workers on `localhost`.

1) Go to **Developer Tools** (Ctrl Shift I / Cmd Opt I), or right-click on any page element, then click **Inspect**.
2) Go to the **Application** tab and then click on Service Workers in the left sidebar. It will list all the registered service workers.
3) Click on "unregister" to uninstall each active service worker.
