### ISSUE TITLE
Update release?

### ISSUE THREAD

**Issue by geoffcorey** [pushy-me/pushy-node#28]
I see in master for package.json
  
  "axios": "^0.28.0"

If I do a `npm install pushy` the package.json says

package.json:    "axios": "^0.27.2"

Looks like a new version needs to be released

**Comment by pushy** [comment]
Hi @geoffcorey,
Thanks for reaching out. We'd be glad to assist.

We've just published version `3.0.4` to `npm` which bumps the `axios` dependency to `0.28.0`.

Please let us know if there's anything else we can help with.

**Comment by geoffcorey** [comment]
Thank you

**Comment by geoffcorey** [comment]
Well that version of axios has a different Snyk warning about critical vulnability.   Axios should probably be updated to 1.73

**Comment by pushy** [comment]
Hi @geoffcorey,
Thanks for bringing this to our attention!

We've just bumped the version of `axios` to the latest which is currently `1.7.3` and published version `4.0.0` to `npm`. The reason for the major version bump is that versions `1.x.x` of `axios` do not support Node.js versions older than `12`.

`snyk test` no longer reports any vulnerabilities.

Please let us know if there's anything else we can help with.
