### ISSUE TITLE
Add pub/sub APIs interface.

### ISSUE THREAD

**Issue by tawfiek** [pushy-me/pushy-node#7]
I think it would be nice to add functionality to the package to make all pushy's functionality available through this package, and avoid the need to make additional requests around it.

I am going to add the pub/sub calls into a clone of this package to use it into my code, I would be my pleasure to add this to yours official package.

**Comment by pushy** [comment]
Hi @tawfiek,
Thanks so much for your contribution! 

We've merged, reformatted, renamed the methods, and published to `npm` as `2.0.11`. The new method names are documented in the [README](https://github.com/pushy-me/pushy-node#additional-api-methods).
